spring:
  application:
   name: taskira
  datasource:
    url: jdbc:postgresql://localhost:5432/taskiradb
    username: taskira
    password: taskira1
    hikari:
      schema: taskira
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org.springframework.transaction: TRACE